PatrikLK/PatrikLK/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from . import settings

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^patrikmain/', include('patrikmain.urls', namespace='patrikmain')),
    # url(r'', 'patrikmain.views.mainpage', name='main_page'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PatrikLK/patrikmain/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login$', views.login, name='login'),
    url(r'^prom_mater$', views.prom_mater, name='prom_mater'),
    url(r'^my_orders$', views.my_orders, name='my_orders'),
    url(r'^my_settings$', views.my_settings, name='my_settings'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^registry', views.registrate, name='registry')
]

PatrikLK/patrikmain/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    farth_name = models.CharField(max_length=64,  verbose_name='Отчество', blank=True)
    phone = models.CharField(max_length=32, verbose_name='Номер телефона')
    yandex_money = models.CharField(max_length=16, verbose_name='Яндекс-кошелек', blank=True)
    web_money = models.CharField(max_length=13, verbose_name='Web money кошелек', blank=True)
    bank_card = models.CharField(max_length=20, verbose_name='Номер карты', blank=True)

class Orders(models.Model):
    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ["orderID"]

    orderID = models.CharField(max_length=5, unique=True, verbose_name='ID заказа', blank=False)
    partnerID = models.ForeignKey(User, verbose_name='Промокод', limit_choices_to={'is_staff': False})
    orderdate = models.DateField(auto_now=False, auto_now_add=False)
    orderstatus = models.BooleanField(verbose_name='Статус выплаты', default=False, blank=False)

class PromMaterials(models.Model):
    class Meta:
        verbose_name = "Реламный материал"
        verbose_name_plural = "Реламный материалы"

    name = models.CharField(max_length=128, unique=True, blank=False, verbose_name='Название материала')
    view = models.FileField(verbose_name='Изображение', upload_to='promMaterials/')

PatrikLK/patrikmain/forms.py
from .models import User
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from datetime import date

class AdminUserAddForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

class AdminUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = "__all__"

PatrikLK/patrikmain/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import QuerySet
from django.shortcuts import render, resolve_url
from django.utils.http import is_safe_url
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash, authenticate,
)
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.template.response import TemplateResponse
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)
from .models import User, Orders, PromMaterials
from datetime import datetime, date, timedelta
from .forms import AdminUserChangeForm


# Create your views here.

# def mainpage(request):
#     return render(request, "patrikmain/patrik/index.html")


@csrf_exempt
def registrate(request):
    params = request.POST
    user = User.objects.create_user(params['login'], params['email'], params['password'], phone=params['phone'])
    return render(request, 'patrikmain/login.html')


@sensitive_post_parameters()
@csrf_protect
@never_cache
def login(request, template_name='patrikmain/login.html',
          redirect_field_name=REDIRECT_FIELD_NAME,
          authentication_form=AuthenticationForm,
          current_app=None, extra_context=None):
    """
    Displays the login form and handles the login action.
    """
    redirect_to = request.POST.get(redirect_field_name,
                                   request.GET.get(redirect_field_name, ''))

    if request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():
            # Ensure the user-originating redirection url is safe.
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)
            # Okay, security check complete. Log the user in.
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect(redirect_to)
    else:
        form = authentication_form(request)

    current_site = get_current_site(request)

    context = {
        'form': form,
        redirect_field_name: redirect_to,
        'site': current_site,
        'site_name': current_site.name,
    }
    if extra_context is not None:
        context.update(extra_context)

    if current_app is not None:
        request.current_app = current_app

    return TemplateResponse(request, template_name, context)


@login_required
def prom_mater(request):
    prom_list = list(PromMaterials.objects.all())
    # print(type(prom_list))
    result = []
    i = 0
    while i < len(prom_list):
        result.append(prom_list[i:i + 4])
        i += 4
    # print(result)
    return render(request, "patrikmain/prom_mater.html", {'active': 'prom',
                                                          'cur_user': request.user.username,
                                                          'result': result,
                                                          'media': settings.MEDIA_ROOT})


@login_required
def my_orders(request):
    orders_list = Orders.objects.filter(partnerID=User.objects.get(username=request.user.username).id)
    paginate = Paginator(orders_list, 50)
    page = request.GET.get('page')
    try:
        orders = paginate.page(page)
    except PageNotAnInteger:
        orders = paginate.page(1)
    except EmptyPage:
        orders = paginate.page(paginate.num_pages)
    summa = len(orders_list)
    # print(summa)
    return render(request, "patrikmain/orders.html", {'active': "my_orders", 'result': orders,
                                                      'cur_user': request.user.username})


@login_required
def my_settings(request):
    cur_user = User.objects.get(username=request.user.username)
    if request.method == "POST":
        user_param = request.POST
        cur_user.username = user_param['username']
        cur_user.first_name = user_param['first_name']
        cur_user.last_name = user_param['last_name']
        cur_user.farth_name = user_param['farth_name']
        cur_user.phone = user_param['phone']
        cur_user.yandex_money = user_param['yandex_money']
        cur_user.web_money = user_param['web_money']
        cur_user.bank_card = user_param['bank_card']
        cur_user.save()
        return render(request, "patrikmain/settings.html", {'result': cur_user,
                                                            'cur_user': cur_user,
                                                            'active': 'settings'})
    else:
        return render(request, "patrikmain/settings.html", {'result': cur_user,
                                                            'cur_user': cur_user,
                                                            'active': 'settings'})


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/patrikmain/login')

PatrikLK/patrikmain/templates/patrikmain/login.html
{% extends "patrikmain/main_base.html" %}
{% load staticfiles %}

<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>

<body>

{% block branding %}
    <div id="branding" style="float: none">
    <img src="{% static 'img/logo.png' %}" align="center" id="logo-login"> {# Добавить прям сюда стиль #}
    </div>
{% endblock %}

{% block menu %}
{% endblock %}

{% block person %}
{% endblock %}

<div id="container">
    {% block container %}

        {% block content %}

            <div id="main">
                <form id="login" action='{% url "patrikmain:login" %}' method="post">
                {% csrf_token %}
                    <div class="form-row">
                        <img src="{% static 'img/login.png' %} "><input type="text" name="username" class="text-in">
                    </div>
                    <div class="form-row">
                        <img src="{% static 'img/lock.png' %}"><input type="password" name="password" class="text-in">
                        <input type="hidden" name="next" value="{{ next }}" />
                    </div>
                    <div class="submit-row">
                        <label>&nbsp;</label><input type="submit" value="Вперед!" class="button_main"/>
                    </div>
                </form>
            </div>

        {% endblock %}

    {% endblock %}
</div>

{% block footer %}
{% endblock %}
</body>

</html>

PatrikLK/patrikmain/templates/patrikmain/main_base.html
{% load staticfiles %}

{% block extrastyle %}{% endblock %}
<style>

</style>

<html>
<head lang="en">
    <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/main.css" %}{% endblock %}" />
    <meta charset="UTF-8">
    <title>Patrikman</title>
    <link href="{% static 'js/lightgallery/skins/default/style.css' %}" type="text/css" media="screen" rel="stylesheet" />
    <script src="{% static 'js/lightgallery/lightgallery.min.js'%}" type="text/javascript"></script>
    <script>lightgallery.init();</script>

<script type="text/javascript">

</script>

</head>
<body>
<div id="header">

    {% block branding %}
        <div id="branding">
            <img src="{% static 'img/logo.png' %}" align="center">
        </div>
    {% endblock %}

    <div id="menu">
        {% block menu %}
                <a {% if active == 'prom' %} id="active" {% endif %} class="link"  href="{% url 'patrikmain:prom_mater' %}"><img src="{% static 'img/prom.png' %}">Рекламные материалы</a>
                <a {% if active == 'my_orders' %} id="active" {% endif %} class="link"  href="{% url 'patrikmain:my_orders' %}"><img src="{% static 'img/bonus.png' %}">Бонусы</a>
                <a {% if active == 'settings' %} id="active" {% endif %} class="link" href="{% url 'patrikmain:my_settings' %}"><img src="{% static 'img/my_data.png' %}">Мои данные</a>
        {% endblock %}


            {% block person %}
                <div id="person">
                <img src="{% static 'img/person.png' %}" align="center">
                {% if cur_user %} Вы зашли как: <a href="{% url 'patrikmain:my_settings' %}">{{ cur_user }}</a>
                    <a href="{% url 'patrikmain:logout' %}"><img src="{% static 'img/exit.png' %}" align="center"> </a>
                {% endif %}
                </div>
            {% endblock %}

    </div>



</div>

{% block container %}

    {% block content %}
    {% endblock %}

{% endblock %}

{% block footer %}
{% endblock %}
</body>
</html>

PatrikLK/patrikmain/templates/patrikmain/orders.html
{% extends "patrikmain/main_base.html" %}
{% load staticfiles %}

<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>

<body>
{% block container %}
    {% block content %}
        <div id="content-main">
            {% if result %}

                <div class="paginator-up">
                    <span class="step_links">
                        {% if result.has_previous %}
                            {% if result.previous_page_number != 1 %}
                                <a href="?page=1" class="page_link">1</a>
                                <span>...</span>
                            {% endif %}
                            <a href="?page={{ result.previous_page_number }}" class="page_link">{{ result.previous_page_number }}</a>
                        {% endif %}
                        <span class="cur_page">{{ result.number }}</span>
                        {% if result.has_next%}
                            <a href="?page={{ result.next_page_number }}" class="page_link">{{ result.next_page_number }}</a>
                            {% if result.next_page_number != result.paginator.num_pages %}
                                <span>...</span>
                                <a href="?page={{ result.paginator.num_pages }}" class="page_link">{{ result.paginator.num_pages }}</a>
                            {% endif %}
                        {% endif %}
                    </span>
                </div>

                    <table id="bonus">
                        <thead>
                            <td class="order-cell">Номер заказа</td><td class="order-cell">Дата заказа</td><td class="order-cell">Статус</td>
                        </thead>
                        <tbody>
                        {% for foo in result %}
                            <tr class="row">
                                <td class="order-cell">{{ foo.orderID }}</td><td class="order-cell">{{ foo.orderdate }}</td>
                                {% if foo.orderstatus %}<td class="order-cell" style="color: rgb(16, 195, 2)"> Выплачен
                                {% else %} <td class="order-cell" style="color: rgb(195, 2, 57)">Не выплачен
                                {% endif %} </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                <div class="paginator-down">
                    <span class="step_links">
                        {% if result.has_previous %}
                            {% if result.previous_page_number != 1 %}
                                <a href="?page=1" class="page_link">1</a>
                                <span>...</span>
                            {% endif %}
                            <a href="?page={{ result.previous_page_number }}" class="page_link">{{ result.previous_page_number }}</a>
                        {% endif %}
                        <span class="cur_page">{{ result.number }}</span>
                        {% if result.has_next%}
                            <a href="?page={{ result.next_page_number }}" class="page_link">{{ result.next_page_number }}</a>
                            {% if result.next_page_number != result.paginator.num_pages %}
                                <span>...</span>
                                <a href="?page={{ result.paginator.num_pages }}" class="page_link">{{ result.paginator.num_pages }}</a>
                            {% endif %}
                        {% endif %}
                    </span>
                </div>

            {% endif %}
        </div>
    {% endblock %}
{% endblock %}
</body>
</html>

PatrikLK/patrikmain/templates/patrikmain/prom_mater.html
{% extends "patrikmain/main_base.html" %}

<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>

<body>
{% block container %}
    {% block content %}

    {% if result %}
        <table id="prom_table">

        {% for res in result %}
            <tr class="image">{% for foo in res%}<td><a href="{{ foo.view.url }}" rel="lightgallery" title="{{ foo.name }}"><img src="{{ foo.view.url }}" width="210" height="126"></a></td>{% endfor %}</tr>
            <tr>{% for foo in res%}<td><a href="{{ foo.view.url }}" download="{{ foo.name }}" class="name">Скачать {{ foo.name }}</a></td>{% endfor %}</tr>

        {% endfor %}
        </table>
    {% endif %}
    {% endblock %}
{% endblock %}
</body>
</html>

PatrikLK/patrikmain/templates/patrikmain/settings.html
{% extends "patrikmain/main_base.html" %}

<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>

<body>
    {% block container %}
        {% block content %}
            <div id="content-main">
            {% if result %}
                <form id="set_change" action="" method="post">
                    {% csrf_token %}
                    <table id="setting_form">
                        <tr>
                            <td class="input-name">Логин</td>
                            <td class="input-name">Номер телефона</td>
                        </tr>
                        <tr>
                            <td><input class="vtextfield" name="username" type="text" value="{{ result.username }}"></td>
                            <td><input class="vtextfield" name="phone" type="text" value="{{ result.phone }}"></td>
                        </tr>
                        <tr>
                            <td class="input-name">Имя</td>
                            <td class="input-name">Яндекс-кошелек</td>
                        </tr>
                        <tr>
                            <td><input class="vtextfield" name="first_name" type="text" value="{{ result.first_name }}"></td>
                            <td><input class="vtextfield" name="yandex_money" type="text" value="{{ result.yandex_money }}"></td>
                        </tr>
                        <tr>
                            <td class="input-name">Фамилия</td>
                            <td class="input-name">Кошелек web-money</td>
                        </tr>
                        <tr>
                            <td><input class="vtextfield" name="last_name" type="text" value="{{ result.last_name }}"></td>
                            <td><input class="vtextfield" name="web_money" type="text" value="{{ result.web_money }}"></td>
                        </tr>
                        <tr>
                            <td class="input-name">Отчество</td>
                            <td class="input-name">Номер карты</td>
                        </tr>
                        <tr>
                            <td><input class="vtextfield" name="farth_name" type="text" value="{{ result.farth_name }}"></td>
                            <td><input class="vtextfield" name="bank_card" type="text" value="{{ result.bank_card }}"></td>
                        </tr>
                        <tr>
                            <td><input class="button_main" type="submit" value="Изменить"></td>
                        </tr>
                    </table>
                </form>
            {% endif %}
            </div>
        {% endblock %}
    {% endblock %}
</body>